server:
  port: 8080

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Reservation
          uri: http://localhost:8081
          predicates:
            - Path=/reservation/** 
        - id: Pay
          uri: http://localhost:8082
          predicates:
            - Path=/pay/** 
        - id: Store
          uri: http://localhost:8083
          predicates:
            - Path=/product/** 
        - id: View
          uri: http://localhost:8084
          predicates:
            - Path= /dashboard/**
        - id: Supplier
          uri: http://localhost:8085
          predicates:
            - Path=/stock/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservation/** 
        - id: Pay
          uri: http://pay:8080
          predicates:
            - Path=/pay/** 
        - id: Store
          uri: http://store:8080
          predicates:
            - Path=/product/** 
        - id: View
          uri: http://view:8080
          predicates:
            - Path= /dashboard/**
        - id: Supplier
          uri: http://supplier:8080
          predicates:
            - Path=/stock/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080