apiVersion: apps/v1
kind: Deployment
metadata:
  name: Supplier
  labels:
    app: Supplier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Supplier
  template:
    metadata:
      labels:
        app: Supplier
    spec:
      containers:
        - name: Supplier
          image: username/Supplier:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5