---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Reservation
  labels:
    app: Reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Reservation
  template:
    metadata:
      labels:
        app: Reservation
    spec:
      containers:
        - name: Reservation
          image: username/Reservation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Pay
  labels:
    app: Pay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Pay
  template:
    metadata:
      labels:
        app: Pay
    spec:
      containers:
        - name: Pay
          image: username/Pay:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Store
  labels:
    app: Store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Store
  template:
    metadata:
      labels:
        app: Store
    spec:
      containers:
        - name: Store
          image: username/Store:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: View
  labels:
    app: View
spec:
  replicas: 1
  selector:
    matchLabels:
      app: View
  template:
    metadata:
      labels:
        app: View
    spec:
      containers:
        - name: View
          image: username/View:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Supplier
  labels:
    app: Supplier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Supplier
  template:
    metadata:
      labels:
        app: Supplier
    spec:
      containers:
        - name: Supplier
          image: username/Supplier:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Reservation
  labels:
    app: Reservation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Reservation


---


apiVersion: v1
kind: Service
metadata:
  name: Pay
  labels:
    app: Pay
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Pay


---


apiVersion: v1
kind: Service
metadata:
  name: Store
  labels:
    app: Store
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Store


---


apiVersion: v1
kind: Service
metadata:
  name: View
  labels:
    app: View
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: View


---


apiVersion: v1
kind: Service
metadata:
  name: Supplier
  labels:
    app: Supplier
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Supplier

