apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: 422489764856.dkr.ecr.ca-central-1.amazonaws.com/user-dongjin-reservation:cab3bd8f0c35079837f45e866c4f80413c041d36
          ports:
            - containerPort: 8080
